version: '3'
services:
  redis:
    image: redis:6.2.0
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - support-net

  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    ports:
      - '8081:8081'
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: local:redis:6379
    networks:
      - support-net

networks:
  support-net:
    driver: bridge
